title: Invites
template: invites
icon: ?open

options:
  url: false
  status: false
  delete: false
  
sections:
    drafts:
      extends: sections/invites
      headline: Unpublished popup set
      status: drafts

    unlisted:
      extends: sections/invites
      headline: Unlisted popup set
      status: unlisted

    listed:
      extends: sections/invites
      headline: Published popup set
      status: published

    fields:
        extends: fields/main_instructions
          
